# Generated by Django 3.1.2 on 2021-01-28 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0001_create_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(help_text='identify category', primary_key=True, serialize=False)),
                ('amount', models.BigIntegerField(default=1, help_text='amount anything')),
                ('register_class', models.CharField(choices=[('coins', 'CollectedCoin'), ('monsters', 'KilledMonster'), ('deaths', 'Death')], help_text='anything class to count', max_length=50)),
                ('register_field', models.CharField(blank=True, help_text='if want to count anything of a class', max_length=50, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awards.category')),
            ],
            options={
                'db_table': 'levels',
            },
        ),
    ]
