# Generated by Django 3.1.2 on 2021-01-28 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('awards', '0003_create_trophy_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='trophyuser',
            name='value_register_field',
            field=models.CharField(blank=True, help_text='value if count by a field', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trophyuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trophies', to=settings.AUTH_USER_MODEL),
        ),
    ]
