# Generated by Django 3.1.2 on 2021-01-30 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0004_add_register_value_field_in_trophy'),
    ]

    operations = [
        migrations.AddField(
            model_name='trophy',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, help_text='register datetime win trophy', null=True),
        ),
    ]
