# Generated by Django 3.1.2 on 2021-01-27 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectedCoin',
            fields=[
                ('id', models.BigAutoField(help_text='identify collected coin', primary_key=True, serialize=False)),
                ('value', models.FloatField(help_text='coin value')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'collected_coin',
            },
        ),
    ]
