# Generated by Django 3.1.2 on 2021-01-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0001_create_collected_coin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.BigAutoField(help_text='identify monster', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='name monster', max_length=255)),
            ],
            options={
                'db_table': 'monsters',
            },
        ),
    ]
