# Generated by Django 3.1.2 on 2021-01-27 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registers', '0002_create_monster'),
    ]

    operations = [
        migrations.CreateModel(
            name='KilledMonster',
            fields=[
                ('id', models.BigAutoField(help_text='identify killed monster', primary_key=True, serialize=False)),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registers.monster')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Killed_monster',
            },
        ),
    ]
