# Generated by Django 3.1.2 on 2021-01-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0004_create_death'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectedcoin',
            name='value',
            field=models.FloatField(default=10, help_text='coin value'),
        ),
    ]
