# Generated by Django 3.1.2 on 2021-01-28 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(help_text='identify category', primary_key=True, serialize=False)),
                ('description', models.CharField(help_text='description category', max_length=255)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
    ]
