# Generated by Django 3.1.2 on 2021-01-28 03:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('awards', '0002_create_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trophy',
            fields=[
                ('id', models.BigAutoField(help_text='identify Trophy', primary_key=True, serialize=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awards.category')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awards.level')),
            ],
            options={
                'db_table': 'trophies',
            },
        ),
        migrations.CreateModel(
            name='TrophyUser',
            fields=[
                ('id', models.BigAutoField(help_text='identify Trophy User', primary_key=True, serialize=False)),
                ('trophy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awards.trophy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trophy_user',
            },
        ),
    ]
