# Generated by Django 3.1.2 on 2021-01-28 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registers', '0005_add_default_value_coin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectedcoin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='death',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deaths', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='killedmonster',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dead_monsters', to=settings.AUTH_USER_MODEL),
        ),
    ]
